# AI-Based Chocolate Paan Sales Prediction System Using Machine Learning
## Week 1: Problem Definition & Dataset Exploration

In [1]:
import numpy as np
import pandas as pd
print("NumPy:",np.__version__)
print("Pandas:",pd.__version__)

NumPy: 2.3.5
Pandas: 2.3.3

In [2]:
df=pd.read_excel("Chocolate_Paan_Sales_Dataset_10000.xlsx")
df.head()

,Date,Day_of_Week,Month,Weekend,Festival,Season,Temperature,Rainfall,Price,Discount_Percentage,Instagram_Reel,YouTube_Video,Facebook_Ads,Marketing_Budget,Returning_Customers,New_Customers,Online_Orders,Offline_Orders,Customer_Rating,Boxes_Sold
0,2024-01-01,Monday,1,0,0,Winter,28.3,10.0,120,0,1,0,1,3175,119,51,22,102,4.2,160
1,2024-01-02,Tuesday,1,0,0,Winter,24.0,16.9,100,10,0,1,1,2565,80,34,33,37,4.5,172
2,2024-01-03,Wednesday,1,0,0,Winter,24.9,17.8,110,10,1,0,0,3972,105,58,79,36,4.7,181
3,2024-01-04,Thursday,1,0,1,Winter,24.0,13.8,140,15,1,0,0,1212,116,43,45,102,4.3,237
4,2024-01-05,Friday,1,0,0,Winter,20.5,2.8,110,10,1,1,0,1357,14,44,65,110,3.8,170

## Q1. Shape of dataset

In [3]:
df.shape

(10000, 20)

## Q2. Column names

In [4]:
df.columns

Index(['Date', 'Day_of_Week', 'Month', 'Weekend', 'Festival', 'Season',
       'Temperature', 'Rainfall', 'Price', 'Discount_Percentage',
       'Instagram_Reel', 'YouTube_Video', 'Facebook_Ads', 'Marketing_Budget',
       'Returning_Customers', 'New_Customers', 'Online_Orders',
       'Offline_Orders', 'Customer_Rating', 'Boxes_Sold'],
      dtype='object')

## Q3. Data types

In [5]:
df.dtypes

Date                    object
Day_of_Week             object
Month                    int64
Weekend                  int64
Festival                 int64
Season                  object
Temperature            float64
Rainfall               float64
Price                    int64
Discount_Percentage      int64
Instagram_Reel           int64
YouTube_Video            int64
Facebook_Ads             int64
Marketing_Budget         int64
Returning_Customers      int64
New_Customers            int64
Online_Orders            int64
Offline_Orders           int64
Customer_Rating        float64
Boxes_Sold               int64
dtype: object

## Q4. Dataset info

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 10000 non-null  object
 1   Day_of_Week          10000 non-null  object
 2   Month                10000 non-null  int64
 3   Weekend              10000 non-null  int64
 4   Festival             10000 non-null  int64
 5   Season               10000 non-null  object
 6   Temperature          10000 non-null  float64
 7   Rainfall             10000 non-null  float64
 8   Price                10000 non-null  int64
 9   Discount_Percentage  10000 non-null  int64
 10  Instagram_Reel       10000 non-null  int64
 11  YouTube_Video        10000 non-null  int64
 12  Facebook_Ads         10000 non-null  int64
 13  Marketing_Budget     10000 non-null  int64
 14  Returning_Customers  10000 non-null  int64
 15  New_Customers        10000 non-null  int64
 16  Online_Orders        10000 non-null  int64
 17  Offline_Orders       10000 non-null  int64
 18  Customer_Rating      10000 non-null  float64
 19  Boxes_Sold           10000 non-null  int64
dtypes: float64(3), int64(14), object(3)
memory usage: 1.5+ MB

## Q5. Statistical summary

In [7]:
df.describe()

,Month,Weekend,Festival,Temperature,Rainfall,Price,Discount_Percentage,Instagram_Reel,YouTube_Video,Facebook_Ads,Marketing_Budget,Returning_Customers,New_Customers,Online_Orders,Offline_Orders,Customer_Rating,Boxes_Sold
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,6.460600,0.284900,0.073300,28.809750,35.089050,119.990000,10.045000,0.494800,0.504100,0.495700,2753.857700,65.111400,42.790200,52.487200,64.951800,4.248280,165.049900
std,3.452135,0.451389,0.260641,5.642198,50.808562,14.134351,7.054995,0.499998,0.500008,0.500007,1301.183268,32.409104,21.828294,27.624952,32.129449,0.430234,36.989196
min,1.000000,0.000000,0.000000,18.000000,0.000000,100.000000,0.000000,0.000000,0.000000,0.000000,500.000000,10.000000,5.000000,5.000000,10.000000,3.500000,48.000000
25%,3.000000,0.000000,0.000000,24.700000,6.900000,110.000000,5.000000,0.000000,0.000000,0.000000,1627.750000,37.000000,24.000000,28.000000,37.000000,3.900000,140.000000
50%,6.000000,0.000000,0.000000,28.700000,13.400000,120.000000,10.000000,0.000000,1.000000,0.000000,2761.500000,65.000000,43.000000,52.000000,64.000000,4.200000,164.000000
75%,9.000000,1.000000,0.000000,32.700000,20.000000,130.000000,15.000000,1.000000,1.000000,1.000000,3875.250000,93.000000,61.000000,77.000000,93.000000,4.600000,189.000000
max,12.000000,1.000000,1.000000,40.000000,200.000000,140.000000,20.000000,1.000000,1.000000,1.000000,4999.000000,120.000000,80.000000,100.000000,120.000000,5.000000,311.000000

## Q6. First 10 rows

In [8]:
df.head(10)

,Date,Day_of_Week,Month,Weekend,Festival,Season,Temperature,Rainfall,Price,Discount_Percentage,Instagram_Reel,YouTube_Video,Facebook_Ads,Marketing_Budget,Returning_Customers,New_Customers,Online_Orders,Offline_Orders,Customer_Rating,Boxes_Sold
0,2024-01-01,Monday,1,0,0,Winter,28.3,10.0,120,0,1,0,1,3175,119,51,22,102,4.2,160
1,2024-01-02,Tuesday,1,0,0,Winter,24.0,16.9,100,10,0,1,1,2565,80,34,33,37,4.5,172
2,2024-01-03,Wednesday,1,0,0,Winter,24.9,17.8,110,10,1,0,0,3972,105,58,79,36,4.7,181
3,2024-01-04,Thursday,1,0,1,Winter,24.0,13.8,140,15,1,0,0,1212,116,43,45,102,4.3,237
4,2024-01-05,Friday,1,0,0,Winter,20.5,2.8,110,10,1,1,0,1357,14,44,65,110,3.8,170
5,2024-01-06,Saturday,1,1,0,Winter,24.9,19.5,110,10,1,0,1,754,34,73,34,107,4.3,197
6,2024-01-07,Sunday,1,1,0,Winter,23.0,3.3,140,20,0,0,0,1671,22,45,68,75,4.4,134
7,2024-01-08,Monday,1,0,0,Winter,27.7,11.8,110,0,1,1,0,4006,120,36,44,24,4.1,166
8,2024-01-09,Tuesday,1,0,0,Winter,22.8,18.2,130,15,1,0,0,1267,81,16,34,39,4.8,133
9,2024-01-10,Wednesday,1,0,0,Winter,19.4,18.9,140,20,0,0,1,2691,20,62,6,45,4.5,118

## Q7. Last 10 rows

In [9]:
df.tail(10)

,Date,Day_of_Week,Month,Weekend,Festival,Season,Temperature,Rainfall,Price,Discount_Percentage,Instagram_Reel,YouTube_Video,Facebook_Ads,Marketing_Budget,Returning_Customers,New_Customers,Online_Orders,Offline_Orders,Customer_Rating,Boxes_Sold
9990,2025-05-15,Thursday,5,0,0,Summer,32.6,7.7,130,20,0,1,0,4435,18,26,100,33,4.4,146
9991,2025-05-16,Friday,5,0,0,Summer,30.9,19.8,110,15,1,0,1,4465,19,5,60,11,4.5,144
9992,2025-05-17,Saturday,5,1,0,Summer,30.1,16.5,110,10,0,0,1,2602,96,77,35,90,3.6,212
9993,2025-05-18,Sunday,5,1,0,Summer,38.5,6.2,120,5,1,0,1,2268,111,24,11,75,4.4,174
9994,2025-05-19,Monday,5,0,0,Summer,32.9,17.1,110,10,1,0,0,749,20,24,29,27,4.1,91
9995,2025-05-20,Tuesday,5,0,0,Summer,31.7,8.7,140,10,1,1,1,802,103,12,60,52,4.9,163
9996,2025-05-21,Wednesday,5,0,0,Summer,31.4,13.0,120,10,0,0,0,4473,36,41,38,58,3.8,113
9997,2025-05-22,Thursday,5,0,0,Summer,39.3,4.3,100,20,1,1,0,4460,120,32,50,52,4.0,225
9998,2025-05-23,Friday,5,0,0,Summer,39.1,16.0,120,20,1,0,0,3091,111,47,40,118,3.8,208
9999,2025-05-24,Saturday,5,1,0,Summer,39.8,6.4,120,0,0,1,1,3783,16,35,49,48,3.9,128

## Q8. Missing values

In [10]:
df.isnull().sum()

Date                   0
Day_of_Week            0
Month                  0
Weekend                0
Festival               0
Season                 0
Temperature            0
Rainfall               0
Price                  0
Discount_Percentage    0
Instagram_Reel         0
YouTube_Video          0
Facebook_Ads           0
Marketing_Budget       0
Returning_Customers    0
New_Customers          0
Online_Orders          0
Offline_Orders         0
Customer_Rating        0
Boxes_Sold             0
dtype: int64

## Q9. Unique Seasons

In [11]:
df['Season'].unique()

array(['Winter', 'Summer', 'Monsoon'], dtype=object)

## Q10. Season counts

In [12]:
df['Season'].value_counts()

Season
Winter     4137
Summer     3379
Monsoon    2484
Name: count, dtype: int64

## Q11. Average Boxes Sold

In [13]:
df['Boxes_Sold'].mean()

np.float64(165.0499)

## Q12. Max Marketing Budget

In [14]:
df['Marketing_Budget'].max()

4999

## Q13. Min Marketing Budget

In [15]:
df['Marketing_Budget'].min()

500

## Q14. Festival records

In [16]:
df[df['Festival']==1].head()

,Date,Day_of_Week,Month,Weekend,Festival,Season,Temperature,Rainfall,Price,Discount_Percentage,Instagram_Reel,YouTube_Video,Facebook_Ads,Marketing_Budget,Returning_Customers,New_Customers,Online_Orders,Offline_Orders,Customer_Rating,Boxes_Sold
3,2024-01-04,Thursday,1,0,1,Winter,24.0,13.8,140,15,1,0,0,1212,116,43,45,102,4.3,237
23,2024-01-24,Wednesday,1,0,1,Winter,29.2,14.5,130,15,0,0,0,1883,17,24,85,71,4.6,158
26,2024-01-27,Saturday,1,1,1,Winter,26.7,2.2,110,10,0,1,0,3799,59,14,42,117,3.9,239
63,2024-03-04,Monday,3,0,1,Summer,34.0,6.9,100,0,1,0,1,3196,108,26,60,102,4.4,240
64,2024-03-05,Tuesday,3,0,1,Summer,37.6,18.5,120,20,0,0,1,1298,21,39,67,102,4.7,213

## Q15. Weekend & Discount >10

In [17]:
df[(df['Weekend']==1)&(df['Discount_Percentage']>10)].head()

,Date,Day_of_Week,Month,Weekend,Festival,Season,Temperature,Rainfall,Price,Discount_Percentage,Instagram_Reel,YouTube_Video,Facebook_Ads,Marketing_Budget,Returning_Customers,New_Customers,Online_Orders,Offline_Orders,Customer_Rating,Boxes_Sold
6,2024-01-07,Sunday,1,1,0,Winter,23.0,3.3,140,20,0,0,0,1671,22,45,68,75,4.4,134
19,2024-01-20,Saturday,1,1,0,Winter,26.6,5.6,120,15,1,0,0,3270,35,60,88,93,4.6,211
27,2024-01-28,Sunday,1,1,0,Winter,21.4,16.8,100,15,0,0,1,2467,12,49,17,75,4.6,151
47,2024-02-17,Saturday,2,1,0,Winter,22.0,4.6,140,20,1,0,0,4276,36,38,94,100,4.8,198
48,2024-02-18,Sunday,2,1,0,Winter,22.6,16.9,100,15,1,0,1,2144,33,59,14,28,4.2,178

## Q16. Average Boxes Sold by Season

In [18]:
df.groupby('Season')['Boxes_Sold'].mean()

Season
Monsoon    163.853462
Summer     163.787807
Winter     166.799130
Name: Boxes_Sold, dtype: float64

## Q17. Correlation

In [19]:
df.corr(numeric_only=True)

,Month,Weekend,Festival,Temperature,Rainfall,Price,Discount_Percentage,Instagram_Reel,YouTube_Video,Facebook_Ads,Marketing_Budget,Returning_Customers,New_Customers,Online_Orders,Offline_Orders,Customer_Rating,Boxes_Sold
Month,1.000000,0.005760,0.079960,-0.277559,0.216724,0.011388,0.003255,-0.004580,0.015187,0.011809,-0.011191,-0.006406,0.017915,0.018019,-0.001293,-0.003493,0.038682
Weekend,0.005760,1.000000,-0.011758,0.017998,-0.003588,-0.011467,0.002883,-0.003849,-0.013817,0.018943,-0.019028,-0.000700,0.006361,0.001323,0.008836,0.002086,0.303913
Festival,0.079960,-0.011758,1.000000,-0.106536,-0.045585,0.011601,0.001197,0.004076,-0.006527,0.001268,-0.006378,-0.011646,-0.010270,0.012319,0.012102,-0.013457,0.414177
Temperature,-0.277559,0.017998,-0.106536,1.000000,-0.023339,-0.022873,0.018881,-0.003632,-0.017730,-0.003723,0.008928,0.021681,-0.001043,0.000598,0.003754,0.002237,-0.021166
Rainfall,0.216724,-0.003588,-0.045585,-0.023339,1.000000,-0.006942,0.004598,-0.010172,0.004245,0.000578,-0.000424,0.011005,0.004221,0.000585,-0.020420,0.010058,-0.014951
Price,0.011388,-0.011467,0.011601,-0.022873,-0.006942,1.000000,-0.002854,-0.002555,0.011893,-0.006940,0.006787,-0.008495,0.021274,0.005030,0.012131,-0.003489,-0.297453
Discount_Percentage,0.003255,0.002883,0.001197,0.018881,0.004598,-0.002854,1.000000,-0.010991,-0.004447,0.009127,-0.001074,-0.014848,-0.002221,-0.008254,0.003279,0.004836,0.371279
Instagram_Reel,-0.004580,-0.003849,0.004076,-0.003632,-0.010172,-0.002555,-0.010991,1.000000,-0.015316,-0.014291,0.002519,0.012780,-0.007641,0.021529,-0.002736,-0.000832,0.244860
YouTube_Video,0.015187,-0.013817,-0.006527,-0.017730,0.004245,0.011893,-0.004447,-0.015316,1.000000,-0.005530,0.012799,-0.005583,0.008692,-0.018731,-0.001133,-0.004639,0.183190
Facebook_Ads,0.011809,0.018943,0.001268,-0.003723,0.000578,-0.006940,0.009127,-0.014291,-0.005530,1.000000,-0.006786,0.004516,-0.004554,0.009832,0.016372,-0.014842,0.141965
Marketing_Budget,-0.011191,-0.019028,-0.006378,0.008928,-0.000424,0.006787,-0.001074,0.002519,0.012799,-0.006786,1.000000,0.001900,0.007415,0.009941,-0.008332,-0.006688,0.172664
Returning_Customers,-0.006406,-0.000700,-0.011646,0.021681,0.011005,-0.008495,-0.014848,0.012780,-0.005583,0.004516,0.001900,1.000000,0.009530,0.011277,0.004761,0.017150,0.352005
New_Customers,0.017915,0.006361,-0.010270,-0.001043,0.004221,0.021274,-0.002221,-0.007641,0.008692,-0.004554,0.007415,0.009530,1.000000,-0.002379,0.016885,-0.008889,0.289061
Online_Orders,0.018019,0.001323,0.012319,0.000598,0.000585,0.005030,-0.008254,0.021529,-0.018731,0.009832,0.009941,0.011277,-0.002379,1.000000,0.019290,0.003237,0.236506
Offline_Orders,-0.001293,0.008836,0.012102,0.003754,-0.020420,0.012131,0.003279,-0.002736,-0.001133,0.016372,-0.008332,0.004761,0.016885,0.019290,1.000000,0.013632,0.191005
Customer_Rating,-0.003493,0.002086,-0.013457,0.002237,0.010058,-0.003489,0.004836,-0.000832,-0.004639,-0.014842,-0.006688,0.017150,-0.008889,0.003237,0.013632,1.000000,0.002010
Boxes_Sold,0.038682,0.303913,0.414177,-0.021166,-0.014951,-0.297453,0.371279,0.244860,0.183190,0.141965,0.172664,0.352005,0.289061,0.236506,0.191005,0.002010,1.000000

## Q18. Sort by Boxes Sold

In [20]:
df.sort_values(by='Boxes_Sold',ascending=False).head(10)

,Date,Day_of_Week,Month,Weekend,Festival,Season,Temperature,Rainfall,Price,Discount_Percentage,Instagram_Reel,YouTube_Video,Facebook_Ads,Marketing_Budget,Returning_Customers,New_Customers,Online_Orders,Offline_Orders,Customer_Rating,Boxes_Sold
6849,2024-10-06,Sunday,10,1,1,Winter,18.7,9.3,100,20,1,1,1,4212,16,39,99,102,4.1,311
2218,2024-01-29,Monday,1,0,1,Winter,21.8,9.0,140,20,1,1,1,4348,109,67,99,71,3.9,306
1072,2024-12-08,Sunday,12,1,1,Winter,22.1,17.3,110,20,1,1,0,1884,93,60,59,111,4.5,305
3570,2025-10-12,Sunday,10,1,1,Winter,27.9,1.8,110,10,1,1,1,4949,109,64,47,47,4.4,300
4292,2025-10-04,Saturday,10,1,1,Winter,22.0,5.3,100,15,1,1,1,3018,110,24,59,113,4.6,300
366,2025-01-01,Wednesday,1,0,1,Winter,22.7,15.5,100,10,1,1,0,1643,108,79,64,113,4.5,299
8519,2025-05-04,Sunday,5,1,0,Summer,30.5,14.3,100,20,1,1,0,3277,115,80,92,102,4.4,297
7613,2024-11-09,Saturday,11,1,1,Winter,23.5,19.0,130,15,1,1,0,4079,53,57,98,105,4.2,294
9043,2024-10-10,Thursday,10,0,1,Winter,18.0,16.6,110,15,1,1,1,4330,116,65,76,93,3.6,293
9726,2024-08-24,Saturday,8,1,1,Monsoon,26.2,169.7,100,20,1,0,1,1898,85,62,29,111,4.6,290

## Q19. Random Sample

In [21]:
df.sample(10)

,Date,Day_of_Week,Month,Weekend,Festival,Season,Temperature,Rainfall,Price,Discount_Percentage,Instagram_Reel,YouTube_Video,Facebook_Ads,Marketing_Budget,Returning_Customers,New_Customers,Online_Orders,Offline_Orders,Customer_Rating,Boxes_Sold
1180,2025-03-26,Wednesday,3,0,0,Summer,33.1,16.8,110,20,0,0,0,1754,43,19,40,10,4.8,117
8638,2025-08-31,Sunday,8,1,1,Monsoon,28.7,170.4,120,20,1,0,1,3533,67,10,73,24,4.9,247
6855,2024-10-12,Saturday,10,1,0,Winter,24.3,13.7,100,10,1,0,0,1947,101,78,49,63,3.8,207
8842,2024-03-23,Saturday,3,1,0,Summer,32.0,17.4,120,20,0,0,0,4273,63,77,18,37,3.7,179
6658,2024-03-29,Friday,3,0,0,Summer,35.2,8.5,140,10,1,1,1,3591,74,13,65,107,4.4,172
2389,2024-07-18,Thursday,7,0,0,Monsoon,26.2,175.8,110,0,1,0,1,931,111,37,82,47,4.7,152
9036,2024-10-03,Thursday,10,0,1,Winter,23.6,3.3,100,5,1,0,0,1360,96,25,44,112,4.5,232
4986,2025-08-29,Friday,8,0,1,Monsoon,30.2,166.0,100,0,1,0,0,1056,59,10,43,105,3.9,188
4345,2025-11-26,Wednesday,11,0,0,Winter,28.9,5.3,110,0,0,1,0,1237,23,78,76,60,4.8,145
4909,2025-06-13,Friday,6,0,0,Summer,32.0,15.9,120,10,1,0,0,4254,100,52,48,38,4.4,174

## Q20. NumPy Array

In [22]:
sales=[120,150,175,200,180]
arr=np.array(sales)
print(arr)
print(arr.shape)

[120 150 175 200 180]
(5,)